# Setup
title:               'Amphibia Archive'
tagline:             ''
description:         'Unofficial blog aggregating the development and creation of Amphibia!'
url:                 https://archive.boonchuy.com
baseurl:             ''
paginate:            3
permalink:           pretty

# About/contact
author:
  name:              Anne Boonchuy
  url:               https://boonchuy.com/
  email:             anne@boonchuy.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
